<?php
$pieces = explode("/", $_SERVER['REQUEST_URI']);

// if($pieces[1] == '') {
//   $lang = 'ru';
// } else if($pieces[1] != 'uz' || $pieces[1] != 'en') {
//   $lang = 'ru';
//   print_r($lang);
// } else if ($pieces[1] == 'uz' || $pieces[1] == 'en') {
//   $lang = $pieces[1];
// }

switch ($pieces[1]) {
  case 'ru':
    $lang = 'ru';
    break;
  case 'uz':
    $lang = 'uz';
    break;
  case 'en':
    $lang = 'en';
    break;
  default:
  $lang = 'ru';
    break;
}
// print_r($pieces[1]);

switch($lang){
  case 'uz':
    $langArray=array();
    $langArray['map'] = 'Xarita';
    $langArray['profile'] = 'Profil';
    $langArray['main'] = 'Asosiy';
    $langArray['logoText'] = 'Elektron navbat partali';
    $langArray['searchText'] = 'Tashkilotlarda xizmatlar qidirish';
    $langArray['search'] = 'Qidirmoq...';
    $langArray['homeBtnOne'] = "Oldindan navbatga yo'zilish";
    $langArray['homeBtnTwo'] = 'Elektron chiptani olish';
    $langArray['empty'] = "Bo'sh";
    $langArray['prOne'] = 'Mening elektron chiptalarim';
    $langArray['prTwo'] = 'Mening buyurtmalarim';
    $langArray['yourTicket'] = 'Sizning chiptangiz';
    $langArray['statusYes'] = 'Holat: Faol';
    $langArray['statusNo'] = 'Holati: Faol emas';
    $langArray['statusСalled'] = 'Holati: ';
    $langArray['statusСlosed'] = "Holati: Yo'piq";
    $langArray['yourBoTicket'] = 'Sizning buyurtmangiz';
    $langArray['number'] = 'Nomer';
    $langArray['branch'] = 'Filial';
    $langArray['address'] = 'Manzil';
    $langArray['service'] = 'Xizmat';
    $langArray['validUntil'] = 'Yaroqlilik muddati';
    $langArray['deleteBtnET'] = "ELEKTRON CHIPTANI O'CHIRISH";
    $langArray['deteleText'] = "CHIPTA O'CHIRILDI";
    $langArray['listOfServices'] = "Xizmatlar ro'yxati";
    $langArray['eTicket'] = 'Elektron chiptalarim';
    $langArray['service'] = 'Xizmat';
    $langArray['receive'] = 'Qabul qilish';
    $langArray['choose'] = 'TANLASH';
    $langArray['information'] = "Ma'lumot";
    $langArray['closeText'] = "Hozirda siz elektron chipta ololmaysiz. Iltimos, ish vaqtida qayting.";
    $langArray['booking'] =  "Navbatga yo'zilish";
    $langArray['personalInformation'] = "Shaxsiy ma'lumot";
    $langArray['bookingData'] =  "Ma'lumotlarni bron qilish";
    $langArray['service'] = 'Xizmat';
    $langArray['date'] = 'Sana';
    $langArray['time'] = 'Vaqt';
    $langArray['next'] = 'KEYINGISI';
    $langArray['name'] = 'Ism';
    $langArray['surname'] = 'Familiya';
    $langArray['phone'] = 'Telefon raqam';
    $langArray['bookADate'] = 'TASDIQLASH';
    $langArray['successfulBooking'] = 'Buyurtma muvaffaqiyatli qilindi';
    $langArray['bookingCode'] = 'Buyurtma kodi';
    $langArray['copied'] = 'Nusxa olingan';
    $langArray['textClick'] = 'Buyurtma kodini nusxalash uchun bosing!';
    $langArray['textPlease'] = 'Buyurtmangiz tafsilotlari SMS orqali yuboriladi';
    $langArray['textWe'] = 'Iltimos, buyurtmangiz codini saqlab oling, bankga tashrif qilganingizda bilet ustuniga kiriting';
    $langArray['textAlready'] = 'Sizda tugallanmagan chipta bor';
    $langArray['close'] = 'YOPISH';
    $langArray['everybody'] = 'HAMMASI';
    $langArray['workingHours'] = 'Ish vaqti';
    $langArray['monday'] = 'Dushanba';
    $langArray['tuesday'] = 'Seshanba';
    $langArray['wednesday'] = 'Chorshanba';
    $langArray['thursday'] = 'Payshanba';
    $langArray['friday'] = 'Juma';
    $langArray['saturday'] = 'Shanba';
    $langArray['sunday'] = 'Yakshanba';
    $langArray['authorization'] = "Ro'yxatdan o'tish";
    $langArray['enterCode'] = 'Kod telegram bot orqali yuborildi';
    $langArray['confirm'] = 'Tasdiqlash';
    $langArray['textTelegram'] = 'Telegram botga kiring va avtorizatsiya uchun raqamingizni yuboring';
    $langArray['textAlready'] = 'Sizda tugallanmagan chipta bor';
    break;
  case 'ru':
    $langArray=array();
    $langArray['map'] = 'Карта';
    $langArray['profile'] = 'Профиль';
    $langArray['main'] = 'Главная';
    $langArray['logoText'] = 'Портал электронной очереди';
    $langArray['searchText'] = 'Поиск услуг в организациях';
    $langArray['search'] = 'Поиск...';
    $langArray['homeBtnOne'] = 'Предварительная запись на обслуживание';
    $langArray['homeBtnTwo'] = 'Получить электронный билет';
    $langArray['empty'] = 'Пусто';
    $langArray['prOne'] = 'Мои электронные билеты';
    $langArray['prTwo'] = 'Мои бронирования';
    $langArray['yourTicket'] = 'Ваш билет';
    $langArray['statusYes'] = 'Статус: Активный';
    $langArray['statusNo'] = 'Статус: Неактивный';
    $langArray['statusСalled'] = 'Статус: Вызывается';
    $langArray['statusСlosed'] = 'Статус: Закрыта';
    $langArray['yourBoTicket'] = 'Ваше бронирование';
    $langArray['number'] = 'Номер';
    $langArray['branch'] = 'Филиал';
    $langArray['address'] = 'Адрес';
    $langArray['service'] = 'Услуга';
    $langArray['validUntil'] = 'Действительно до';
    $langArray['deleteBtnET'] = 'УДАЛИТЬ ЭЛЕКТРОННЫЙ БИЛЕТ';
    $langArray['deteleText'] = 'УДАЛЕНО';
    $langArray['listOfServices'] = 'Список услуг';
    $langArray['eTicket'] = 'Электронный билет';
    $langArray['service'] = 'Услуга';
    $langArray['receive'] = 'ПОЛУЧИТЬ';
    $langArray['choose'] = 'ВЫБРАТЬ';
    $langArray['information'] = "Информация";
    $langArray['closeText'] = "В настоящее время вы не можете оформить электронный билет. Пожалуйста, вернитесь в рабочее время";
    $langArray['booking'] =  'Бронирование';
    $langArray['personalInformation'] = 'Персональные данные';
    $langArray['bookingData'] =  'Данные бронирования';
    $langArray['service'] = 'Услуга';
    $langArray['date'] = 'Дата';
    $langArray['time'] = 'Время';
    $langArray['next'] = 'ДАЛЕЕ';
    $langArray['name'] = 'Имя';
    $langArray['surname'] = 'Фамилия';
    $langArray['phone'] = 'Номер телефон';
    $langArray['bookADate'] = 'ЗАБРОНИРОВАТЬ ДАТУ';
    $langArray['successfulBooking'] = 'Успешное бронирование';
    $langArray['bookingCode'] = 'Код бронирования';
    $langArray['copied'] = 'Скопировано';
    $langArray['textClick'] = 'Нажмите, чтобы скопировать код бронирования!';
    $langArray['textPlease'] = 'Вы получите SMS о деталях Вашего бронирования, где вы сможете найти дополнительную информацию';
    $langArray['textWe'] = 'Пожалуйста, сохраните ваш код бронирования для ввода в билетный терминал при посещении банка';
    $langArray['textAlready'] = 'У вас есть незавершеный билет';
    $langArray['close'] = 'ЗАКРЫТЬ';
    $langArray['everybody'] = 'ВСЕ';
    $langArray['workingHours'] = 'Режим работы';
    $langArray['monday'] = 'Понедельник';
    $langArray['tuesday'] = 'Вторник';
    $langArray['wednesday'] = 'Среда';
    $langArray['thursday'] = 'Четверг';
    $langArray['friday'] = 'Пятница';
    $langArray['saturday'] = 'Суббота';
    $langArray['sunday'] = 'Воскресенье';
    $langArray['authorization'] = 'Авторизация';
    $langArray['enterCode'] = 'Код отправили через телеграмм бот';
    $langArray['confirm'] = 'Потвердить';
    $langArray['textTelegram'] = 'Войдите в телеграм бот и отправьте свой номер для Авторизация';
    $langArray['textAlready'] = 'У вас есть незавершеный билет';
  break;
  case 'en':
    $langArray['map'] = 'Map';
    $langArray['profile'] = 'Profile';
    $langArray['main'] = 'Main';
    $langArray['logoText'] = 'Electronic queue portal';
    $langArray['searchText'] = 'Search for services in organizations';
    $langArray['search'] = 'Search...';
    $langArray['homeBtnOne'] = 'Booking';
    $langArray['homeBtnTwo'] = 'Get an e-Ticket';
    $langArray['empty'] = 'Empty';
    $langArray['prOne'] = 'My e-Tickets';
    $langArray['prTwo'] = 'My bookings';
    $langArray['yourTicket'] = 'Your e-Ticket';
    $langArray['statusYes'] = 'Status: Active';
    $langArray['statusNo'] = 'Status: Inactive';
    $langArray['statusСalled'] = 'Status: Called by';
    $langArray['statusСlosed'] = 'Status: Сlosed';
    $langArray['yourBoTicket'] = 'Your booking';
    $langArray['number'] = 'Number';
    $langArray['branch'] = 'Branch';
    $langArray['address'] = 'Address';
    $langArray['service'] = 'Service';
    $langArray['validUntil'] = 'Valid until';
    $langArray['deleteBtnET'] = 'DELETE ELECTRONIC TICKET';
    $langArray['deteleText'] = 'DELETED';
    $langArray['listOfServices'] = 'List of services';
    $langArray['eTicket'] = 'e-Ticket';
    $langArray['service'] = 'Service';
    $langArray['receive'] = 'RECEIVE';
    $langArray['choose'] = 'CHOOSE';
    $langArray['information'] = "Information";
    $langArray['closeText'] = "Currently you can't draw an e-Ticket. Please go back an appointment for at work time";
    $langArray['booking'] =  'Booking';
    $langArray['personalInformation'] = 'Personal Information';
    $langArray['bookingData'] =  'Booking data';
    $langArray['service'] = 'Service';
    $langArray['date'] = 'Date';
    $langArray['time'] = 'Time';
    $langArray['next'] = 'NEXT';
    $langArray['name'] = 'Name';
    $langArray['surname'] = 'Surname';
    $langArray['phone'] = 'Phone number';
    $langArray['bookADate'] = 'BOOK A DATE';
    $langArray['successfulBooking'] = 'Successful booking';
    $langArray['bookingCode'] = 'Booking code';
    $langArray['copied'] = 'Copied';
    $langArray['textClick'] = 'Click to copy the booking code!';
    $langArray['textPlease'] = 'We will send you by SMS about your booking details, where you can find more information';
    $langArray['textWe'] = 'Please save your booking code for later';
    $langArray['textAlready'] = 'You have an unfinished ticket';
    $langArray['close'] = 'CLOSE';
    $langArray['everybody'] = 'EVERY';
    $langArray['workingHours'] = 'Working hours';
    $langArray['monday'] = 'Monday';
    $langArray['tuesday'] = 'Tuesday';
    $langArray['wednesday'] = 'Wednesday';
    $langArray['thursday'] = 'Thursday';
    $langArray['friday'] = 'Friday';
    $langArray['saturday'] = 'Saturday';
    $langArray['sunday'] = 'Sunday';
    $langArray['authorization'] = 'Authorization';
    $langArray['enterCode'] = 'The code was melted through a telegram bot';
    $langArray['confirm'] = 'Confirm';
    $langArray['textTelegram'] = 'Log in to the telegram bot and send your number for Authorization';
    $langArray['textAlready'] = 'You have an unfinished ticket';
    break;
}
?>